/**
 * Reconstruct one turn from its trace.
 *
 *   npx --cache /tmp/npmcache --yes tsx@4.19.2 scripts/ai-trace-demo.ts
 *
 * The point of a trace id is that a turn can be put back together afterwards.
 * This runs the real loop against a fake model, takes the emitted JSON line, and
 * renders it as the tree — proving the emitted record actually carries enough
 * to reconstruct the sequence, rather than merely claiming it does.
 *
 * No text is generated and nothing is billed.
 */
import fs from "node:fs";
import Module from "node:module";

const require_ = Module.createRequire(import.meta.url);

process.env.ANTHROPIC_API_KEY = "sk-ant-test-key-for-a-fake-client-0000000000000000";
for (const line of fs.readFileSync(".env.local", "utf8").split("\n")) {
  const s = line.trim();
  if (!s || s.startsWith("#") || !s.includes("=")) continue;
  const i = s.indexOf("=");
  const k = s.slice(0, i).trim();
  if (k === "ANTHROPIC_API_KEY") continue;
  process.env[k] = s.slice(i + 1).trim().replace(/^["']|["']$/g, "");
}

interface Scripted {
  text: string;
  tool?: { name: string; input: Record<string, unknown> };
  usage?: Record<string, number>;
}

function installFakeModel(script: Scripted[]) {
  const { Messages } = require_("@anthropic-ai/sdk/resources/messages/messages.js");
  let call = 0;
  Messages.prototype.stream = function () {
    const turn = script[call] ?? { text: "…" };
    call++;
    const content: Record<string, unknown>[] = [{ type: "text", text: turn.text }];
    if (turn.tool) {
      content.push({ type: "tool_use", id: `toolu_${call}`, name: turn.tool.name, input: turn.tool.input });
    }
    return {
      async *[Symbol.asyncIterator]() {
        yield { type: "content_block_delta", index: 0, delta: { type: "text_delta", text: turn.text } };
      },
      async finalMessage() {
        return {
          role: "assistant",
          content,
          stop_reason: turn.tool ? "tool_use" : "end_turn",
          usage: turn.usage ?? { input_tokens: 1400, output_tokens: 60 },
        };
      },
    };
  };
}

async function main() {
  const obs = await import("../lib/ai/observability");

  installFakeModel([
    { text: "Let me look. ", tool: { name: "search_products", input: { query: "linen saree" } }, usage: { input_tokens: 1352, output_tokens: 48 } },
    { text: "And its story. ", tool: { name: "search_brand_knowledge", input: { query: "kasavu" } }, usage: { input_tokens: 2180, output_tokens: 41 } },
    { text: "Here you are — the Kasavu, ₹4,500, in stock.", usage: { input_tokens: 3010, output_tokens: 205 } },
  ]);

  const { streamChat } = await import("../lib/chat");
  let emitted: import("../lib/ai/observability").AiTrace | null = null;
  const rec = obs.beginTrace({ model: "claude-sonnet-5", emit: (t) => (emitted = t) });
  rec.setCaller("customer");

  for await (const _ of streamChat([{ role: "user", content: "do you have linen, and is it real?" }], {
    recorder: rec,
    email: "verified@example.com",
  })) {
    void _;
  }
  rec.finish(rec.firstToolError() ?? (rec.toolCallCount > 0 ? "successful_with_tools" : "successful_no_tool"));

  const t = emitted as unknown as import("../lib/ai/observability").AiTrace;

  const out: string[] = [];
  const w = (s = "") => out.push(s);

  w("# Trace reconstruction");
  w();
  w("Generated by `scripts/ai-trace-demo.ts` — the real loop, a fake model, nothing billed.");
  w();
  w("## The emitted line");
  w();
  w("One JSON object on stdout per request, discriminated by `evt`:");
  w();
  w("```json");
  w(JSON.stringify({ evt: "ai_trace", ...t }, null, 2));
  w("```");
  w();
  w("## Reconstructed");
  w();
  w("```");
  w(`TRACE ${t.trace_id}`);
  w(`  ${t.surface} · ${t.caller} · ${t.model} · flag=${t.feature_enabled}`);

  // Interleave by the order they actually happened: call 0, its tools, call 1, …
  // A tool call belongs to the model call that asked for it, which is the call
  // at the same index — the loop runs one batch of lookups per round.
  const maxIdx = Math.max(t.calls.length, t.tools.length);
  for (let i = 0; i < maxIdx; i++) {
    const c = t.calls[i];
    if (c) {
      const last = i === maxIdx - 1 && t.tools.length <= i;
      w(
        `  ${last ? "└─" : "├─"} model call ${c.index} · ${c.latency_ms}ms · in ${c.input_tokens} / out ${c.output_tokens} · stop=${c.stop_reason} · tools_offered=${c.tools_offered}${c.error ? ` · ERROR ${c.error}` : ""}`
      );
    }
    const tool = t.tools[i];
    if (tool) {
      w(
        `  │   └─ tool ${tool.index} · ${tool.tool} · ${tool.latency_ms}ms · found=${tool.found} · ok=${tool.ok} · privileged=${tool.privileged}${tool.error ? ` · ERROR ${tool.error}` : ""}`
      );
    }
  }
  w(`  └─ outcome: ${t.outcome}`);
  w(
    `     ${t.model_calls} model calls · ${t.tool_calls} tools · ${t.total_tokens} tokens · $${t.cost_usd?.toFixed(5)} · ${t.total_latency_ms}ms total (${t.model_latency_ms}ms model, ${t.tool_latency_ms}ms tools)`
  );
  w("```");
  w();
  w("## What is deliberately absent");
  w();
  w("The customer's question, the tool arguments (`linen saree`, `kasavu`), the session");
  w("email and the tool results appear nowhere above. The recorder has no parameter that");
  w("could carry them — see the header of `lib/ai/observability.ts`.");
  w();

  fs.mkdirSync("reports/ai-observability", { recursive: true });
  fs.writeFileSync("reports/ai-observability/trace-example.md", out.join("\n"));
  console.log(out.join("\n"));
  console.log("\nWritten to reports/ai-observability/trace-example.md");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
